#!/usr/bin/env bash

# Function to setup Terraform
function setup_util_terraform() (
    source "$DOROTHY/sources/bash.bash"

    # improve performance for detectable utilities with conditional assets
    if setup-util "$@" --check --cli=terraform; then
        return 0
    fi

    # Function to get the latest version of Terraform
    function get_latest_version {
        curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep -Po '"tag_name": "\K.*?(?=")'
    }

    # setup
    local arch version options=(
        --cli='terraform'
        "$@"
        AUR='terraform'
        BREW='terraform'
        PORT='terraform'
        SCOOP='terraform'
        PKG='terraform'
        PKGIN='terraform'
        PKGADD='terraform'
    )

    version=$(get_latest_version)
    version=${version#v}  # Remove leading 'v' if present

    function add_download_option {
        local platform="$1" extension="$2"
        local url="https://releases.hashicorp.com/terraform/${version}/terraform_${version}_${platform}.${extension}"
        options+=(
            DOWNLOAD="$url"
            DOWNLOAD_UNZIP_FORMAT='auto'
            DOWNLOAD_ARCHIVE_GLOB='terraform'
        )
    }

    arch="$(get-arch)"
    if is-mac; then
        if test "$arch" = 'a64'; then
            add_download_option 'darwin_arm64' 'zip'
        elif test "$arch" = 'x64'; then
            add_download_option 'darwin_amd64' 'zip'
        fi
    elif is-linux; then
        if test "$arch" = 'a64'; then
            add_download_option 'linux_arm64' 'zip'
        elif test "$arch" = 'x64'; then
            add_download_option 'linux_amd64' 'zip'
        elif test "$arch" = 'x32'; then
            add_download_option 'linux_386' 'zip'
        fi
    elif is-windows; then
        if test "$arch" = 'x64'; then
            add_download_option 'windows_amd64' 'zip'
        elif test "$arch" = 'x32'; then
            add_download_option 'windows_386' 'zip'
        fi
    fi

    setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_terraform "$@"
fi
